server:
  port: 8081
  servlet:
    context-path: /shop
    multipart:
      max-file-size: 10MB  #单个文件
      max-request-size: 100MB #总文件大小

spring:
     datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db_shopmaster?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
     jpa:
       show-sql: true
     mvc:
       view:
         prefix: /WEB-INF/views/
         suffix: .jsp
  #rabbitmq
     rabbitmq:
       host:  127.0.0.1
       port:   5672
       username:  guest
       password:  guest
       ## 消息发送确认机制
       publisher-confirm-type:  correlated
       publisher-returns:  true
    ## 消息回复确认机制
     listener:
      simple:
         acknowledge-mode:  manual

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhang.ssmschoolshop.entity
   #devtools插件
devtools:
    restart:
      enabled: true #是否支持热部署
#mybaatis分页插件pagehelper设置
pagehelper:
  pagehelperDialect: mysql
  reasonable: true
  support-methods-arguments: true

  # 打印sql
logging:
    level:
       com.zhang.ssmschoolshop.dao: DEBUG


mail:
  host: smtp.qq.com
  username: 1452212104@qq.com
  password: ngwtfshywjpajihi1  ### 你的邮件smtp授权码
  default-encoding: UTF-8
  protocol: smtp
  properties:
    mail:
      smtp:
        ssl:
          enable: true
  #spring.mail.port: 25
  from: 1452212105@qq.com
  receive:  1452212101@qq.com #收件者邮箱
  receive2: 1452212102@qq.com
  test-connection: false






